### ISSUE TITLE
Moving to new organization

### ISSUE THREAD

**Issue by dpo** [JuliaOptimizers/CUTEst.jl#47]
@abelsiqueira I'm about to move this repository to another organization of mine. It shouldn't affect you much. It should be sufficient to add the new repo address as an upstream.

**Comment by abelsiqueira** [comment]
Thanks for the heads up.
I don't have permission set on this one though.

**Comment by dpo** [comment]
Should be good now?

**Comment by abelsiqueira** [comment]
All good, thanks.
