### ISSUE TITLE
Use AbstractNLPModel

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaOptimizers/CUTEst.jl#53]
For compatibility with [NLPModels.jl](https://github.com/JuliaOptimizers/NLPModels.jl/) and [Optimize.jl](https://github.com/JuliaOptimizers/Optimize.jl).
See [this](https://drive.google.com/file/d/0B93L4n2eB78POUdjZUtNd3BnYlk/view?usp=sharing)

**Comment by dpo** [comment]
Is this done now?

**Comment by abelsiqueira** [comment]
Done
